name: Maven seperate
on: [push]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven compile
        run: mvn compile
      - name: Maven test
        run: mvn test